# Generated by Django 4.1.4 on 2025-10-13 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accept_language', models.CharField(blank=True, max_length=255)),
                ('referer', models.URLField(blank=True)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('cookie_enabled', models.BooleanField(default=False)),
                ('screen_resolution', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('hardware_concurrency', models.IntegerField(blank=True, null=True)),
                ('device_memory', models.FloatField(blank=True, null=True)),
                ('camera_access', models.BooleanField(default=False)),
                ('microphone_access', models.BooleanField(default=False)),
                ('geolocation_access', models.BooleanField(default=False)),
                ('notifications_access', models.BooleanField(default=False)),
                ('clipboard_access', models.BooleanField(default=False)),
                ('webgl_vendor', models.TextField(blank=True)),
                ('webgl_renderer', models.TextField(blank=True)),
                ('available_fonts', models.TextField(blank=True)),
                ('canvas_fingerprint', models.TextField(blank=True)),
                ('audio_support', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('clipboard_data', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'user_data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(max_length=100)),
                ('granted', models.BooleanField(default=False)),
                ('additional_data', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_logs', to='main.userdata')),
            ],
            options={
                'db_table': 'permission_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdvancedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=100)),
                ('data_key', models.CharField(max_length=255)),
                ('data_value', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_data', to='main.userdata')),
            ],
            options={
                'db_table': 'advanced_data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
