# Generated by Django 4.1.4 on 2025-10-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('accept_language', models.CharField(blank=True, max_length=255, null=True)),
                ('referer', models.TextField(blank=True, null=True)),
                ('is_secure', models.BooleanField(default=False)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='permissionlog',
            name='user_data',
        ),
        migrations.DeleteModel(
            name='AdvancedData',
        ),
        migrations.DeleteModel(
            name='PermissionLog',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
